=== wakystuf/ESG-Mod/Endless Space Competitive Mod/Schemas/DiplomaticRelationState.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Datatable" />
  <xs:element name="DiplomaticRelationState" nillable="true" type="DiplomaticRelationState" />
  <xs:complexType name="DiplomaticRelationState">
    <xs:complexContent mixed="false">
      <xs:extension base="DatatableElement">
        <xs:sequence>
          <xs:element minOccurs="0" maxOccurs="1" name="DiplomaticPressureEffectReference" type="XmlNamedReference" />
          <xs:element minOccurs="0" maxOccurs="unbounded" name="DiplomaticAbilityChange" type="DiplomaticAbilityChange" />
          <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element minOccurs="0" maxOccurs="1" name="PrerequisiteTransition" type="DiplomaticRelationStatePrerequisiteTransition" />
            <xs:element minOccurs="0" maxOccurs="1" name="TurnTransition" type="DiplomaticRelationStateTurnsTransition" />
          </xs:choice>
        </xs:sequence>
        <xs:attribute default="0" name="StateEvaluation" type="xs:float" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="XmlNamedReference">
    <xs:attribute name="Name" type="xs:string" />
  </xs:complexType>
  <xs:complexType name="DiplomaticAbilityChange">
    <xs:sequence>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element minOccurs="0" maxOccurs="1" name="PathPrerequisite" type="PathPrerequisite" />
        <xs:element minOccurs="0" maxOccurs="1" name="InterpreterPrerequisite" type="InterpreterPrerequisite" />
      </xs:choice>
    </xs:sequence>
    <xs:attribute default="Add" name="Operation" type="AbilityOperation" />
    <xs:attribute name="DiplomaticAbilityReference" type="xs:string" />
  </xs:complexType>
  <xs:complexType name="PathPrerequisite">
    <xs:simpleContent>
      <xs:extension base="Prerequisite" />
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="Prerequisite">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute default="false" name="Inverted" type="xs:boolean" />
        <xs:attribute name="Flags" type="xs:string" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="InterpreterPrerequisite">
    <xs:simpleContent>
      <xs:extension base="Prerequisite" />
    </xs:simpleContent>
  </xs:complexType>
  <xs:simpleType name="AbilityOperation">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Add" />
      <xs:enumeration value="Remove" />
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="DiplomaticRelationStatePrerequisiteTransition">
    <xs:complexContent mixed="false">
      <xs:extension base="DiplomaticRelationStateTransition">
        <xs:sequence>
          <xs:element minOccurs="0" maxOccurs="unbounded" name="PathPrerequisite" type="PathPrerequisite" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="DiplomaticRelationStateTransition">
    <xs:attribute name="DestinationState" type="xs:string" />
  </xs:complexType>
  <xs:complexType name="DiplomaticRelationStateTurnsTransition">
    <xs:complexContent mixed="false">
      <xs:extension base="DiplomaticRelationStateTransition">
        <xs:attribute name="Duration" type="xs:int" use="required" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="DatatableElement">
    <xs:attribute name="Name" type="xs:string" />
  </xs:complexType>
</xs:schema>

=== wakystuf/ESG-Mod/Endless Space Competitive Mod/Diplomacy/DiplomaticRelationStates[Major].xml
<?xml version="1.0" encoding="utf-8" ?>
<Datatable xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xsi:noNamespaceSchemaLocation="../Schemas/DiplomaticRelationState.xsd">
  <DiplomaticRelationState Name="DiplomaticRelationStatePeace" StateEvaluation="5">
    <DiplomaticPressureEffectReference Name="PressurePeace" />

    <DiplomaticAbilityChange Operation="Add"    DiplomaticAbilityReference="Peace" />
    <DiplomaticAbilityChange Operation="Add"    DiplomaticAbilityReference="IsKnown" />
    <DiplomaticAbilityChange Operation="Add"    DiplomaticAbilityReference="AttackInfluencedFleets" />
    <DiplomaticAbilityChange Operation="Add"    DiplomaticAbilityReference="AttackInfluencedSystems" />
    <DiplomaticAbilityChange Operation="Add"    DiplomaticAbilityReference="SiegeInfluencedSystems" />
    <DiplomaticAbilityChange Operation="Add"    DiplomaticAbilityReference="FriendlyInfluence" />
    <DiplomaticAbilityChange Operation="Add"    DiplomaticAbilityReference="Migration" />
    <DiplomaticAbilityChange Operation="Add"    DiplomaticAbilityReference="GuardProtect" />
    <DiplomaticAbilityChange Operation="Add"    DiplomaticAbilityReference="DropLootOnSystem" />
    <DiplomaticAbilityChange Operation="Add"    DiplomaticAbilityReference="RelayTradingRoutes" />
    <DiplomaticAbilityChange Operation="Add"    DiplomaticAbilityReference="WelcomeFleetsAfterRetreat" />
    <DiplomaticAbilityChange Operation="Add"    DiplomaticAbilityReference="CaptureSystemsWithInfluence" />
    <DiplomaticAbilityChange Operation="Add"    DiplomaticAbilityReference="CanRootStarSystems" />
    <DiplomaticAbilityChange Operation="Add"    DiplomaticAbilityReference="ColonizeHuntingGrounds" />

    <DiplomaticAbilityChange Operation="Remove" DiplomaticAbilityReference="Unknown" />
    <DiplomaticAbilityChange Operation="Remove" DiplomaticAbilityReference="Truce" />
    <DiplomaticAbilityChange Operation="Remove" DiplomaticAbilityReference="ColdWar" />
    <DiplomaticAbilityChange Operation="Remove" DiplomaticAbilityReference="HotWar" />
    <DiplomaticAbilityChange Operation="Remove" DiplomaticAbilityReference="War" />
    <DiplomaticAbilityChange Operation="Remove" DiplomaticAbilityReference="MajorWar" />
    <DiplomaticAbilityChange Operation="Remove" DiplomaticAbilityReference="Alliance" />
    <DiplomaticAbilityChange Operation="Remove" DiplomaticAbilityReference="Team" />
    <DiplomaticAbilityChange Operation="Remove" DiplomaticAbilityReference="UnitRecovery" />
    <DiplomaticAbilityChange Operation="Remove" DiplomaticAbilityReference="AttackOwnedFleets" />
    <DiplomaticAbilityChange Operation="Remove" DiplomaticAbilityReference="AttackOwnedSystems" />
    <DiplomaticAbilityChange Operation="Remove" DiplomaticAbilityReference="SiegeOwnedSystems" />
    <DiplomaticAbilityChange Operation="Remove" DiplomaticAbilityReference="GuardBlockade" />
    <DiplomaticAbilityChange Operation="Remove" DiplomaticAbilityReference="BlockTradingRoutes" />
    <DiplomaticAbilityChange Operation="Remove" DiplomaticAbilityReference="RaidSystem" />
    <DiplomaticAbilityChange Operation="Remove" DiplomaticAbilityReference="HostileInfluence" />
    <DiplomaticAbilityChange Operation="Remove" DiplomaticAbilityReference="NeutralInfluence" />
    <DiplomaticAbilityChange Operation="Remove" DiplomaticAbilityReference="CanIntercept" />
    <DiplomaticAbilityChange Operation="Remove" DiplomaticAbilityReference="CitadelsBlockFreeMove" />
    <DiplomaticAbilityChange Operation="Remove" DiplomaticAbilityReference="WarExhaustCompensation" />
    <DiplomaticAbilityChange Operation="Remove" DiplomaticAbilityReference="BreakDiplomaticTributes" />
    <DiplomaticAbilityChange Operation="Remove" DiplomaticAbilityReference="ShareScience" />
    <DiplomaticAbilityChange Operation="Remove" DiplomaticAbilityReference="BlockOutpostBuyout" />
    <DiplomaticAbilityChange Operation="Remove" DiplomaticAbilityReference="CanDestroyOwnedPlanets" />
    <DiplomaticAbilityChange Operation="Remove" DiplomaticAbilityReference="CanDestroyInfluencedPlanets" />
    <DiplomaticAbilityChange Operation="Remove" DiplomaticAbilityReference="AllowFactionPacts" />
    <DiplomaticAbilityChange Operation="Remove" DiplomaticAbilityReference="FactionPact"/>
    <DiplomaticAbilityChange Operation="Remove" DiplomaticAbilityReference="SharePortalsEvenWithoutTrait"/>
    <DiplomaticAbilityChange Operation="Remove" DiplomaticAbilityReference="ProvideBonusDeploymentLimit"/>

    <PrerequisiteTransition DestinationState="DiplomaticRelationStateColdWar">
      <PathPrerequisite Inverted="false" Flags="Prerequisite">ClassEmpire,FactionTraitEternalWar/ClassSenate/ClassSenator,!Politics03</PathPrerequisite>
    </PrerequisiteTransition>
  </DiplomaticRelationState>

  <DiplomaticRelationState Name="DiplomaticRelationStateColdWar" StateEvaluation="4">
    <DiplomaticAbilityChange Operation="Add"    DiplomaticAbilityReference="ColdWar" />
    <DiplomaticAbilityChange Operation="Add"    DiplomaticAbilityReference="IsKnown" />
    <DiplomaticAbilityChange Operation="Add"    DiplomaticAbilityReference="AttackOwnedFleets" />
    <DiplomaticAbilityChange Operation="Add"    DiplomaticAbilityReference="SiegeOwnedSystems" />
    <DiplomaticAbilityChange Operation="Add"    DiplomaticAbilityReference="AttackOwnedSystems" />
    <DiplomaticAbilityChange Operation="Add"    DiplomaticAbilityReference="Migration" />
    <DiplomaticAbilityChange Operation="Add"    DiplomaticAbilityReference="GuardBlockade" />
    <DiplomaticAbilityChange Operation="Add"    DiplomaticAbilityReference="BlockTradingRoutes" />
    <DiplomaticAbilityChange Operation="Add"    DiplomaticAbilityReference="RelayTradingRoutes" />
    <DiplomaticAbilityChange Operation="Add"    DiplomaticAbilityReference="RaidSystem" />
    <DiplomaticAbilityChange Operation="Add"    DiplomaticAbilityReference="HostileInfluence" />
    <DiplomaticAbilityChange Operation="Add"    DiplomaticAbilityReference="DropLootOnSystem" />
    <DiplomaticAbilityChange Operation="Add"    DiplomaticAbilityReference="CanIntercept" />
    <DiplomaticAbilityChange Operation="Add"    DiplomaticAbilityReference="CitadelsBlockFreeMove" />
    <DiplomaticAbilityChange Operation="Add"    DiplomaticAbilityReference="OpenBorders" />
    <DiplomaticAbilityChange Operation="Add"    DiplomaticAbilityReference="WelcomeFleetsAfterRetreat" />
    <DiplomaticAbilityChange Operation="Add"    DiplomaticAbilityReference="BlockOutpostBuyout" />
    <DiplomaticAbilityChange Operation="Add"    DiplomaticAbilityReference="CaptureSystemsWithInfluence" />
    <DiplomaticAbilityChange Operation="Add"    DiplomaticAbilityReference="ColonizeHuntingGrounds" />
    <DiplomaticAbilityChange Operation="Add"    DiplomaticAbilityReference="CanRootStarSystems" />

    <DiplomaticAbilityChange Operation="Remove" DiplomaticAbilityReference="FakeCloseBorders" />
    <DiplomaticAbilityChange Operation="Remove" DiplomaticAbilityReference="Unknown" />
    <DiplomaticAbilityChange Operation="Remove" DiplomaticAbilityReference="Truce" />
    <DiplomaticAbilityChange Operation="Remove" DiplomaticAbilityReference="HotWar" />
    <DiplomaticAbilityChange Operation="Remove" DiplomaticAbilityReference="War" />
    <DiplomaticAbilityChange Operation="Remove" DiplomaticAbilityReference="MajorWar" />
    <DiplomaticAbilityChange Operation="Remove" DiplomaticAbilityReference="Peace" />
    <DiplomaticAbilityChange Operation="Remove" DiplomaticAbilityReference="ForcedPeace" />
    <DiplomaticAbilityChange Operation="Remove" DiplomaticAbilityReference="Alliance" />
    <DiplomaticAbilityChange Operation="Remove" DiplomaticAbilityReference="Team" />
    <DiplomaticAbilityChange Operation="Remove" DiplomaticAbilityReference="NeutralInfluence" />
    <DiplomaticAbilityChange Operation="Remove" DiplomaticAbilityReference="FriendlyInfluence" />
    <DiplomaticAbilityChange Operation="Remove" DiplomaticAbilityReference="UnitRecovery" />
    <DiplomaticAbilityChange Operation="Remove" DiplomaticAbilityReference="AttackInfluencedFleets" />
    <DiplomaticAbilityChange Operation="Remove" DiplomaticAbilityReference="AttackInfluencedSystems" />
    <DiplomaticAbilityChange Operation="Remove" DiplomaticAbilityReference="SiegeInfluencedSystems" />
    <DiplomaticAbilityChange Operation="Remove" DiplomaticAbilityReference="GuardProtect" />
    <DiplomaticAbilityChange Operation="Remove" DiplomaticAbilityReference="VisionSharing" />
    <DiplomaticAbilityChange Operation="Remove" DiplomaticAbilityReference="ShareTradingRouteBranches" />
    <DiplomaticAbilityChange Operation="Remove" DiplomaticAbilityReference="ScienceAgreement" />
    <DiplomaticAbilityChange Operation="Remove" DiplomaticAbilityReference="WarExhaustCompensation" />
    <DiplomaticAbilityChange Operation="Remove" DiplomaticAbilityReference="BreakDiplomaticTributes" />
    <DiplomaticAbilityChange Operation="Remove" DiplomaticAbilityReference="ShareScience" />
    <DiplomaticAbilityChange Operation="Remove" DiplomaticAbilityReference="CanDestroyOwnedPlanets" />
    <DiplomaticAbilityChange Operation="Remove" DiplomaticAbilityReference="CanDestroyInfluencedPlanets" />
    <DiplomaticAbilityChange Operation="Remove" DiplomaticAbilityReference="AllowFactionPacts" />
    <DiplomaticAbilityChange Operation="Remove" DiplomaticAbilityReference="FactionPact"/>
    <DiplomaticAbilityChange Operation="Remove" DiplomaticAbilityReference="SharePortalsEvenWithoutTrait"/>
    <DiplomaticAbilityChange Operation="Remove" DiplomaticAbilityReference="ProvideBonusDeploymentLimit"/>
  </DiplomaticRelationState>

  <DiplomaticRelationState Name="DiplomaticRelationStateTruce" StateEvaluation="3">
    <DiplomaticAbilityChange Operation="Add" DiplomaticAbilityReference="Truce" />
    <DiplomaticAbilityChange Operation="Add" DiplomaticAbilityReference="IsKnown" />
