=== wakystuf/ESG-Mod/Endless Space Competitive Mod/Schemas/Droplist.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Datatable" />
  <xs:element name="Droplist" nillable="true" type="Droplist" />
  <xs:complexType name="Droplist">
    <xs:complexContent mixed="false">
      <xs:extension base="DatatableElement">
        <xs:sequence>
          <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element minOccurs="0" maxOccurs="1" name="Relic" type="DroppableRelic" />
            <xs:element minOccurs="0" maxOccurs="1" name="Population" type="DroppablePopulation" />
            <xs:element minOccurs="0" maxOccurs="1" name="Faction" type="DroppableFaction" />
            <xs:element minOccurs="0" maxOccurs="1" name="Play" type="DroppableReferencePlay" />
            <xs:element minOccurs="0" maxOccurs="1" name="Unlock" type="DroppableReferenceUnlock" />
            <xs:element minOccurs="0" maxOccurs="1" name="Hero" type="DroppableReferenceHero" />
            <xs:element minOccurs="0" maxOccurs="1" name="Law" type="DroppableReferenceLaw" />
            <xs:element minOccurs="0" maxOccurs="1" name="Module" type="DroppableModule" />
            <xs:element minOccurs="0" maxOccurs="1" name="Blueprint" type="DroppableBlueprint" />
            <xs:element minOccurs="0" maxOccurs="1" name="Fleet" type="DroppableFleet" />
            <xs:element minOccurs="0" maxOccurs="1" name="Technology" type="DroppableReferenceTechnology" />
            <xs:element minOccurs="0" maxOccurs="1" name="Resource" type="DroppableResource" />
            <xs:element minOccurs="0" maxOccurs="1" name="Integer" type="DroppableInteger" />
            <xs:element minOccurs="0" maxOccurs="1" name="String" type="DroppableString" />
            <xs:element minOccurs="0" maxOccurs="1" name="List" type="DroppableReferenceList" />
          </xs:choice>
        </xs:sequence>
        <xs:attribute default="1" name="Picks" type="xs:int" />
        <xs:attribute default="Weighted" name="Selector" type="DroplistSelector" />
        <xs:attribute default="false" name="RetryOnFailure" type="xs:boolean" />
        <xs:attribute name="Category" type="xs:string" />
        <xs:attribute name="Fallback" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="DroppableRelic">
    <xs:complexContent mixed="false">
      <xs:extension base="Droppable">
        <xs:attribute name="Amount" type="xs:float" use="required" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="Droppable">
    <xs:attribute default="true" name="CanHaveDuplicate" type="xs:boolean" />
    <xs:attribute default="1" name="Weight" type="xs:int" />
    <xs:attribute default="0" name="MaxTurn" type="xs:int" />
  </xs:complexType>
  <xs:complexType name="DroppablePopulation">
    <xs:complexContent mixed="false">
      <xs:extension base="Droppable">
        <xs:attribute name="PopulationName" type="xs:string" />
        <xs:attribute name="Title" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="DroppableFaction">
    <xs:complexContent mixed="false">
      <xs:extension base="Droppable">
        <xs:attribute name="FactionName" type="xs:string" />
        <xs:attribute name="Title" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="DroppableReferenceOfEncounterPlayDefinition">
    <xs:complexContent mixed="false">
      <xs:extension base="Droppable">
        <xs:attribute name="Name" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="DroppableReferencePlay">
    <xs:complexContent mixed="false">
      <xs:extension base="DroppableReferenceOfEncounterPlayDefinition" />
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="DroppableReferenceOfUnlockDatatableElement">
    <xs:complexContent mixed="false">
      <xs:extension base="Droppable">
        <xs:attribute name="Name" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="DroppableReferenceUnlock">
    <xs:complexContent mixed="false">
      <xs:extension base="DroppableReferenceOfUnlockDatatableElement">
        <xs:sequence>
          <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element minOccurs="0" maxOccurs="1" name="StatisticPrerequisite" type="StatisticPrerequisite" />
            <xs:element minOccurs="0" maxOccurs="1" name="DatePrerequisite" type="DatePrerequisite" />
            <xs:element minOccurs="0" maxOccurs="1" name="DownloadableContentPrerequisite" type="DownloadableContentPrerequisite" />
            <xs:element minOccurs="0" maxOccurs="1" name="GameSettingPrerequisite" type="GameSettingPrerequisite" />
            <xs:element minOccurs="0" maxOccurs="1" name="InterpreterPrerequisite" type="InterpreterPrerequisite" />
            <xs:element minOccurs="0" maxOccurs="1" name="PathPrerequisite" type="PathPrerequisite" />
          </xs:choice>
        </xs:sequence>
        <xs:attribute name="SimulationDescriptorReference" type="xs:string" />
        <xs:attribute name="SimulationTag" type="xs:string" />
        <xs:attribute default="true" name="Constrained" type="xs:boolean" />
        <xs:attribute default="false" name="ApplyOnEmpire" type="xs:boolean" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="StatisticPrerequisite">
    <xs:simpleContent>
      <xs:extension base="Prerequisite">
        <xs:attribute default="-3.40282347E+38" name="MinimumValue" type="xs:float" />
        <xs:attribute default="3.40282347E+38" name="MaximumValue" type="xs:float" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="Prerequisite">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute default="false" name="Inverted" type="xs:boolean" />
        <xs:attribute name="Flags" type="xs:string" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="DatePrerequisite">
    <xs:simpleContent>
      <xs:extension base="Prerequisite" />
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="DownloadableContentPrerequisite">
    <xs:simpleContent>
      <xs:extension base="Prerequisite" />
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="GameSettingPrerequisite">
    <xs:simpleContent>
      <xs:extension base="Prerequisite" />
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="InterpreterPrerequisite">
    <xs:simpleContent>
      <xs:extension base="Prerequisite" />
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="PathPrerequisite">
    <xs:simpleContent>
      <xs:extension base="Prerequisite" />
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="DroppableReferenceOfHeroDefinition">
    <xs:complexContent mixed="false">
      <xs:extension base="Droppable">
        <xs:attribute name="Name" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="DroppableReferenceHero">
    <xs:complexContent mixed="false">
      <xs:extension base="DroppableReferenceOfHeroDefinition">
        <xs:attribute default="false" name="Spawn" type="xs:boolean" />
        <xs:attribute default="1" name="Level" type="xs:int" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="DroppableReferenceOfTechnologyDefinition">
    <xs:complexContent mixed="false">
      <xs:extension base="Droppable">
        <xs:attribute name="Name" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="DroppableReferenceLaw">
    <xs:complexContent mixed="false">
      <xs:extension base="DroppableReferenceOfTechnologyDefinition">
        <xs:attribute default="true" name="Constrained" type="xs:boolean" />
        <xs:attribute name="SimulationTag" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="DroppableReferenceTechnology">
    <xs:complexContent mixed="false">
      <xs:extension base="DroppableReferenceOfTechnologyDefinition">
        <xs:attribute default="true" name="Constrained" type="xs:boolean" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="DroppableModule">
    <xs:complexContent mixed="false">
      <xs:extension base="DroppableReferenceTechnology">
        <xs:attribute name="ModuleName" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="DroppableBlueprint">
    <xs:complexContent mixed="false">
      <xs:extension base="DroppableReferenceTechnology">
        <xs:attribute name="ConstructibleName" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="DroppableFleet">
    <xs:complexContent mixed="false">
      <xs:extension base="Droppable">
        <xs:sequence>
          <xs:element minOccurs="0" maxOccurs="1" name="HeroDefinition" type="xs:string" />
          <xs:element minOccurs="0" maxOccurs="unbounded" name="ShipDesign" type="xs:string" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="DroppableResource">
    <xs:complexContent mixed="false">
      <xs:extension base="Droppable">
        <xs:attribute name="Quantity" type="xs:int" use="required" />
        <xs:attribute name="Name" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="DroppableInteger">
    <xs:complexContent mixed="false">
      <xs:extension base="Droppable">
        <xs:attribute name="Value" type="xs:int" use="required" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="DroppableString">
    <xs:complexContent mixed="false">
      <xs:extension base="Droppable">
        <xs:attribute name="Value" type="xs:string" />
        <xs:attribute default="" name="Description" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="DroppableReferenceOfDroplist">
    <xs:complexContent mixed="false">
      <xs:extension base="Droppable">
        <xs:attribute name="Name" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="DroppableReferenceList">
    <xs:complexContent mixed="false">
      <xs:extension base="DroppableReferenceOfDroplist" />
    </xs:complexContent>
  </xs:complexType>
  <xs:simpleType name="DroplistSelector">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Weighted" />
      <xs:enumeration value="Default" />
      <xs:enumeration value="TurnProgression" />
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="DatatableElement">
    <xs:attribute name="Name" type="xs:string" />
  </xs:complexType>
</xs:schema>

=== wakystuf/ESG-Mod/Endless Space Competitive Mod/Quests/Droplists/Droplists[Reward].xml
<?xml version="1.0" encoding="utf-8" ?>
<Datatable xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xsi:noNamespaceSchemaLocation="../../Schemas/Droplist.xsd">
	<!-- Droplists with Terraformation 1 -->
	<Droplist Name="DroplistTechnologyEra2" Selector="Weighted" RetryOnFailure="true" Fallback="DroplistTechnologyEra3">
		<!-- Stage 2 -->
		<Technology Name="TechnologyDefinitionEconomyAndTrade3"                             Weight="1"/>
		<Technology Name="TechnologyDefinitionEconomyAndTrade4"                             Weight="1"/>
		<Technology Name="TechnologyDefinitionEconomyAndTrade4TimeLords"                    Weight="1"/>
		<Technology Name="TechnologyDefinitionEconomyAndTrade5"                             Weight="1"/>
		<Technology Name="TechnologyDefinitionEconomyAndTrade5Vampirilis"                   Weight="1"/>
		<Technology Name="TechnologyDefinitionEconomyAndTrade25"                            Weight="1"/>
		<Technology Name="TechnologyDefinitionEconomyAndTrade25TimeLords"                   Weight="1"/>
		<Technology Name="TechnologyDefinitionEconomyAndTrade25Unfallen"                    Weight="1"/>
		<Technology Name="TechnologyDefinitionEconomyAndTrade25Horatio"                     Weight="1"/>

		<Technology Name="TechnologyDefinitionUnique1"										Weight="1"/>
		<Technology Name="TechnologyDefinitionEmpireDevelopment3"                           Weight="1"/>
		<Technology Name="TechnologyDefinitionEmpireDevelopment3Horatio"                    Weight="1"/>
		<Technology Name="TechnologyDefinitionEmpireDevelopment3Sophons"                    Weight="1"/>
		<Technology Name="TechnologyDefinitionEmpireDevelopment4"                           Weight="1"/>
		<Technology Name="TechnologyDefinitionEmpireDevelopment4Vampirilis"                 Weight="1"/>
		<Technology Name="TechnologyDefinitionEmpireDevelopment5"                           Weight="1"/>
		<Technology Name="TechnologyDefinitionEmpireDevelopment5Unfallen"                   Weight="1"/>
		<Technology Name="TechnologyDefinitionEmpireDevelopment5TimeLords"                  Weight="1"/>

		<Technology Name="TechnologyDefinitionMilitary3"                                    Weight="2"/>
		<Technology Name="TechnologyDefinitionMilitary3Vampirilis"                          Weight="2"/>
		<Technology Name="TechnologyDefinitionMilitary4"                                    Weight="2"/>
		<Technology Name="TechnologyDefinitionMilitary5"                                    Weight="2"/>
		<Technology Name="TechnologyDefinitionMilitary6"                                    Weight="2"/>
		<Technology Name="TechnologyDefinitionMilitary6Unfallen"                            Weight="2"/>

		<Technology Name="TechnologyDefinitionScienceAndExploration25"                      Weight="6"/>
		<Technology Name="TechnologyDefinitionScienceAndExploration25Unfallen"              Weight="6"/>
		<Technology Name="TechnologyDefinitionScienceAndExploration25TimeLords"             Weight="6"/>
		<Technology Name="TechnologyDefinitionScienceAndExploration4"                       Weight="6"/>
		<Technology Name="TechnologyDefinitionScienceAndExploration4Unfallen"               Weight="6"/>
		<Technology Name="TechnologyDefinitionScienceAndExploration4TimeLords"              Weight="6"/>
		<Technology Name="TechnologyDefinitionScienceAndExploration4WormholeUnique"         Weight="6"/>
		<Technology Name="TechnologyDefinitionScienceAndExploration4Wormhole"               Weight="6"/>
		<Technology Name="TechnologyDefinitionScienceAndExploration4UnfallenWormholeUnique" Weight="6"/>
		<Technology Name="TechnologyDefinitionScienceAndExploration4UnfallenWormhole"       Weight="6"/>
		<Technology Name="TechnologyDefinitionScienceAndExploration4TimeLordsWormholeUnique" Weight="6"/>
		<Technology Name="TechnologyDefinitionScienceAndExploration4TimeLordsWormhole"      Weight="6"/>
		<Technology Name="TechnologyDefinitionScienceAndExploration4Vaulters"               Weight="6"/>
		<Technology Name="TechnologyDefinitionScienceAndExploration4VaultersWormholeUnique" Weight="6"/>
		<Technology Name="TechnologyDefinitionScienceAndExploration4VaultersWormhole"       Weight="6"/>
		<Technology Name="TechnologyDefinitionScienceAndExploration5"                       Weight="6"/>
		<Technology Name="TechnologyDefinitionScienceAndExploration5Unfallen"               Weight="6"/>
		<Technology Name="TechnologyDefinitionScienceAndExploration5TimeLords"              Weight="6"/>
		<Technology Name="TechnologyDefinitionScienceAndExploration5Vampirilis"             Weight="6"/>
		<Technology Name="TechnologyDefinitionScienceAndExploration28"                      Weight="6"/>
		<Technology Name="TechnologyDefinitionScienceAndExploration28Unfallen"              Weight="6"/>
		<Technology Name="TechnologyDefinitionScienceAndExploration28TimeLords"             Weight="6"/>
		<Technology Name="TechnologyDefinitionScienceAndExploration28TimeLords2"            Weight="6"/>
		<Technology Name="TechnologyDefinitionScienceAndExploration28Sophons"               Weight="6"/>
		<Technology Name="TechnologyDefinitionScienceAndExploration28Horatio"               Weight="6"/>
		<Technology Name="TechnologyDefinitionScienceAndExploration28"                      Weight="6"/>
		<Technology Name="TechnologyDefinitionScienceAndExploration28TimeLordsSophons"      Weight="6"/>
		<Technology Name="TechnologyDefinitionScienceAndExploration28UnfallenSophons"       Weight="6"/>
		<Technology Name="TechnologyDefinitionScienceAndExploration28UnfallenHoratio"       Weight="6"/>
		<Technology Name="TechnologyDefinitionScienceAndExploration28TimeLordsHoratio"      Weight="6"/>
		<Technology Name="TechnologyDefinitionScienceAndExploration28UnfallenTimeLords"     Weight="6"/>
		<Technology Name="TechnologyDefinitionScienceAndExploration28TimeLordsTimeLords"    Weight="6"/>

		<!-- Stage 3 -->
		<Technology Name="TechnologyDefinitionEconomyAndTrade6"                             Weight="1"/>
		<Technology Name="TechnologyDefinitionEconomyAndTrade6Venetians"                    Weight="1"/>
		<Technology Name="TechnologyDefinitionEconomyAndTrade6Vampirilis"                   Weight="1"/>
		<Technology Name="TechnologyDefinitionEconomyAndTrade6VampirilisVenetians"          Weight="1"/>
		<Technology Name="TechnologyDefinitionEconomyAndTrade7"                             Weight="1"/>
		<Technology Name="TechnologyDefinitionEconomyAndTrade7Horatio"                      Weight="1"/>
		<Technology Name="TechnologyDefinitionEconomyAndTrade7Vampirilis"                   Weight="1"/>
		<Technology Name="TechnologyDefinitionEconomyAndTrade7VampirilisHoratio"            Weight="1"/>
		<Technology Name="TechnologyDefinitionEconomyAndTrade8"                             Weight="1"/>
		<Technology Name="TechnologyDefinitionEconomyAndTrade8TimeLords"                    Weight="1"/>
		<Technology Name="TechnologyDefinitionEconomyAndTrade8Unfallen"                     Weight="1"/>
		<Technology Name="TechnologyDefinitionEconomyAndTrade9"                             Weight="1"/>
		<Technology Name="TechnologyDefinitionEconomyAndTrade11"                            Weight="1"/>
		<Technology Name="TechnologyDefinitionEconomyAndTrade11Vampirilis"                  Weight="1"/>
		<Technology Name="TechnologyDefinitionEconomyAndTrade23"                            Weight="1"/>
		<Technology Name="TechnologyDefinitionEconomyAndTrade23Vampirilis"                  Weight="1"/>

		<Technology Name="TechnologyDefinitionEmpireDevelopment17"                          Weight="1"/>
		<Technology Name="TechnologyDefinitionEmpireDevelopment17Unfallen"                  Weight="1"/>
		<Technology Name="TechnologyDefinitionEmpireDevelopment17TimeLords"                 Weight="1"/>
		<Technology Name="TechnologyDefinitionEmpireDevelopment17Terrans"                   Weight="1"/>
		<Technology Name="TechnologyDefinitionEmpireDevelopment17TerransUnfallen"           Weight="1"/>
		<Technology Name="TechnologyDefinitionEmpireDevelopment17TerransTimeLords"          Weight="1"/>
		<Technology Name="TechnologyDefinitionEmpireDevelopment6"                           Weight="1"/>
		<Technology Name="TechnologyDefinitionEmpireDevelopment6Terrans"                    Weight="1"/>
		<Technology Name="TechnologyDefinitionEmpireDevelopment6Cravers"                    Weight="1"/>
		<Technology Name="TechnologyDefinitionUnique2"										Weight="1"/>
		<Technology Name="TechnologyDefinitionUnique3"										Weight="1"/>
		<Technology Name="TechnologyDefinitionUnique4"										Weight="1"/>
		<Technology Name="TechnologyDefinitionUnique5"										Weight="1"/>

		<Technology Name="TechnologyDefinitionMilitary7"                                    Weight="2"/>
		<Technology Name="TechnologyDefinitionMilitary7Cravers"                             Weight="2"/>
		<Technology Name="TechnologyDefinitionMilitary8"                                    Weight="0"/>
		<Technology Name="TechnologyDefinitionMilitary9"                                    Weight="0"/>
		<Technology Name="TechnologyDefinitionMilitary10"                                   Weight="2"/>
		<Technology Name="TechnologyDefinitionMilitary11"                                   Weight="2"/>
		<Technology Name="TechnologyDefinitionMilitary13"                                   Weight="2"/>
		<Technology Name="TechnologyDefinitionMilitary13Cravers"                            Weight="2"/>
		<Technology Name="TechnologyDefinitionMilitary13Terrans"                            Weight="2"/>

		<Technology Name="TechnologyDefinitionScienceAndExploration6"                       Weight="6"/>
		<Technology Name="TechnologyDefinitionScienceAndExploration6Unfallen"               Weight="6"/>
		<Technology Name="TechnologyDefinitionScienceAndExploration6TimeLords"              Weight="6"/>
		<Technology Name="TechnologyDefinitionScienceAndExploration7"                       Weight="6"/>
