=== wakystuf/ESG-Mod/Endless Space Competitive Mod/Schemas/ResourceDefinition.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Datatable" />
  <xs:element name="ResourceDefinition" nillable="true" type="ResourceDefinition" />
  <xs:complexType name="ResourceDefinition">
    <xs:complexContent mixed="false">
      <xs:extension base="DatatableElement">
        <xs:sequence>
          <xs:element minOccurs="0" maxOccurs="unbounded" name="ResourceLocation" type="ResourceLocationDefinition" />
          <xs:element minOccurs="0" maxOccurs="unbounded" name="ConditionalDescriptorsGroup" type="ResourceConditionalDescriptorGroup" />
        </xs:sequence>
        <xs:attribute name="Type" type="Type" use="required" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="ResourceLocationDefinition">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="1" name="AccumulatorPropertyName" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="MaximumStockPropertyName" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="MinimumStockPropertyName" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="CountPropertyName" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="NetPropertyName" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="StockPropertyName" type="xs:string" />
    </xs:sequence>
    <xs:attribute name="LocationPath" type="xs:string" />
    <xs:attribute name="Name" type="xs:string" />
  </xs:complexType>
  <xs:complexType name="ResourceConditionalDescriptorGroup">
    <xs:sequence>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element minOccurs="0" maxOccurs="1" name="TechnologyPrerequisite" type="TechnologyPrerequisite" />
        <xs:element minOccurs="0" maxOccurs="1" name="InterpreterPrerequisite" type="InterpreterPrerequisite" />
        <xs:element minOccurs="0" maxOccurs="1" name="PathPrerequisite" type="PathPrerequisite" />
      </xs:choice>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="ConditionalDescriptor" type="ResourceConditionalDescriptorDefinition" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="TechnologyPrerequisite">
    <xs:simpleContent>
      <xs:extension base="PathValidityPrerequisite">
        <xs:attribute default="false" name="UnlockHidden" type="xs:boolean" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="PathValidityPrerequisite">
    <xs:simpleContent>
      <xs:extension base="Prerequisite" />
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="Prerequisite">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute default="false" name="Inverted" type="xs:boolean" />
        <xs:attribute name="Flags" type="xs:string" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="InterpreterPrerequisite">
    <xs:simpleContent>
      <xs:extension base="Prerequisite" />
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="PathPrerequisite">
    <xs:simpleContent>
      <xs:extension base="Prerequisite" />
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="ResourceConditionalDescriptorDefinition">
    <xs:sequence>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element minOccurs="0" maxOccurs="1" name="TechnologyPrerequisite" type="TechnologyPrerequisite" />
        <xs:element minOccurs="0" maxOccurs="1" name="InterpreterPrerequisite" type="InterpreterPrerequisite" />
        <xs:element minOccurs="0" maxOccurs="1" name="PathPrerequisite" type="PathPrerequisite" />
      </xs:choice>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="SimulationDescriptorReference" type="SimulationDescriptorReference" />
    </xs:sequence>
    <xs:attribute name="Name" type="xs:string" />
  </xs:complexType>
  <xs:complexType name="SimulationDescriptorReference">
    <xs:complexContent mixed="false">
      <xs:extension base="ValueType">
        <xs:attribute name="Name" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="ValueType" />
  <xs:simpleType name="Type">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Common" />
      <xs:enumeration value="Strategic" />
      <xs:enumeration value="Luxury" />
      <xs:enumeration value="Alias" />
      <xs:enumeration value="Gameplay" />
      <xs:enumeration value="LateCollect" />
      <xs:enumeration value="SystemStrategic" />
      <xs:enumeration value="SystemLuxury" />
      <xs:enumeration value="Academy" />
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="DatatableElement">
    <xs:attribute name="Name" type="xs:string" />
  </xs:complexType>
  <xs:element name="LuxuryResourceDefinition" nillable="true" type="LuxuryResourceDefinition" />
  <xs:complexType name="LuxuryResourceDefinition">
    <xs:complexContent mixed="false">
      <xs:extension base="ResourceDefinition">
        <xs:attribute name="Level" type="xs:int" use="required" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
</xs:schema>

=== wakystuf/ESG-Mod/Endless Space Competitive Mod/Simulation/ResourceDefinitions.xml
<?xml version="1.0" encoding="utf-8" ?>
<Datatable xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xsi:noNamespaceSchemaLocation="../Schemas/ResourceDefinition.xsd">

    <ResourceDefinition Name="EmpireManpower" Type="LateCollect">
        <ResourceLocation Name="EmpireManpower" LocationPath="ClassEmpire">
            <NetPropertyName>TrueNetEmpireManpower</NetPropertyName>
        </ResourceLocation>
    </ResourceDefinition>

	<!-- Resource just to track Enrollment from Manpower -->
    <ResourceDefinition Name="EnrollmentApplied" Type="Common">
        <ResourceLocation Name="EnrollmentApplied" LocationPath="ClassEmpire,EmpireTypeMajor">
            <MaximumStockPropertyName>MaximumEnrollmentApplied</MaximumStockPropertyName>
            <NetPropertyName>NetEnrollmentApplied</NetPropertyName>
            <StockPropertyName>EnrollmentAppliedToFood</StockPropertyName>
        </ResourceLocation>
    </ResourceDefinition>

    <!-- System resources -->
    <ResourceDefinition Name="WarningProgression" Type="Common">
        <ResourceLocation Name="WarningProgression" LocationPath="ClassEmpire/ClassDiplomacy/ClassDiplomaticEmpire">
            <AccumulatorPropertyName>WarningProgressionAccumulator</AccumulatorPropertyName>
            <StockPropertyName>WarningProgressionStock</StockPropertyName>
        </ResourceLocation>
    </ResourceDefinition>
</Datatable>
